Repository Pawang-Euler/Minimarket, pull requests merged in 2020-07, with the labels that each got.

#11 Rules generation
  src/main/java/org/pawaneuler/DataTypes/Rule/AssociationRule.java
  src/main/java/org/pawaneuler/DataTypes/Rule/Rule.java
Labels: enhancement

#13 refactor from suggestion
  src/main/java/org/pawaneuler/DataTypes/Trie/Node.java
  src/main/java/org/pawaneuler/DataTypes/Trie/Trie.java
  src/main/java/org/pawaneuler/Generator/TransactionTrieGenerator/TransactionTrieCreator.java
Labels: Refactoring

#16 add access modifier to constructor
  src/main/java/org/pawaneuler/Generator/TransactionTrieGenerator/TransactionTrieCreator.java
Labels: Refactoring, bug

#14 add Random Generator, Transaction Log Generator, and test file
  src/main/java/org/pawaneuler/Generator/TransactionLogGenerator/RandomGenerator.java
  src/main/java/org/pawaneuler/Generator/TransactionLogGenerator/TransactionLogGenerator.java
  src/main/java/org/pawaneuler/IOTools/TCSVTools/TCSVWriter.java
  src/test/java/org/pawaneuler/Generator/TransactionLogGenerator/RandomGeneratorTest.java
  src/test/java/org/pawaneuler/Generator/TransactionLogGenerator/TransactionLogGeneratorTest.java
  src/test/java/org/pawaneuler/Generator/TransactionLogGenerator/transactionLogTest.tcsv
  src/test/java/org/pawaneuler/Generator/TransactionLogGenerator/transactionLogTest2.tcsv
Labels: enhancement

#21 Rules generation
  Reference/src/Combinations.java
  src/main/java/org/pawaneuler/DataTypes/Rule/AssociationRule.java
  src/main/java/org/pawaneuler/DataTypes/Rule/Combinations.java
  src/main/java/org/pawaneuler/DataTypes/Rule/Frequency.java
  src/main/java/org/pawaneuler/DataTypes/Rule/Rule.java
  src/main/java/org/pawaneuler/DataTypes/Trie/Trie.java
  src/main/java/org/pawaneuler/Generator/AssociationRuleGenerator/AssociationRuleGenerator.java
  src/main/java/org/pawaneuler/Generator/TransactionLogGenerator/RandomGenerator.java
  src/test/java/org/pawaneuler/DataTypes/Rule/RuleGenerationTest.java
  src/test/java/org/pawaneuler/DataTypes/Rule/RuleTest.java
  src/test/java/org/pawaneuler/DataTypes/Rule/Test_100.tcsv
Labels: Refactoring, enhancement

#23 Adding a bit of visual into the program.
  src/main/java/org/pawaneuler/DataTypes/Rule/AssociationRule.java
  src/main/java/org/pawaneuler/Generator/AssociationRuleGenerator/AssociationRuleGenerator.java
  src/main/java/org/pawaneuler/minimarket/App.java
  src/main/java/org/pawaneuler/minimarket/GUI/GenerateMenu.java
  src/main/java/org/pawaneuler/minimarket/GUI/LoadFile.java
  src/main/java/org/pawaneuler/minimarket/GUI/MainMenu.java
  src/main/java/org/pawaneuler/minimarket/GUI/MainProgress.java
  src/main/java/org/pawaneuler/minimarket/GUI/TCSVHandler.java
Labels: enhancement

#28 CES Dataset Experimentation
  pom.xml
  src/main/java/org/pawaneuler/Converter/CESDatasetToTCSVConverter/CESDatasetToTCSVConverter.java
  src/main/java/org/pawaneuler/Converter/CESDatasetToTCSVConverter/README.md
  src/main/java/org/pawaneuler/Generator/AssociationRuleGenerator/AssociationRuleGenerator.java
  src/test/java/org/pawaneuler/Converter/CESDatasetToTCSVConverter/ExampleTest.java
  src/test/java/org/pawaneuler/Converter/CESDatasetToTCSVConverter/example.csv
  src/test/java/org/pawaneuler/DataTypes/Rule/RuleTest.java
  src/test/java/org/pawaneuler/Experimentation/CESDataset/CESDatasetExperimentation.java
  src/test/java/org/pawaneuler/Experimentation/CESDataset/ces_hybrid.csv
  src/test/java/org/pawaneuler/Experimentation/CESDataset/combinationExperimentResult.csv
  src/test/java/org/pawaneuler/Experimentation/CESDataset/example.csv
  src/test/java/org/pawaneuler/Experimentation/CESDataset/experimentResult.csv
  src/test/java/org/pawaneuler/Experimentation/ProgramExecution/ProgramExecutionExperiment.java
  src/test/java/org/pawaneuler/Experimentation/ProgramExecution/testResult.txt
  src/test/java/org/pawaneuler/Experimentation/TransactionLogGenerator/RuntimeTest/RuntimeTest.java
  src/test/java/org/pawaneuler/Experimentation/TransactionLogGenerator/RuntimeTest/runtimeTestResult.txt
  src/test/java/org/pawaneuler/Experimentation/TransactionLogGenerator/StressTest/StressTest.java
  src/test/java/org/pawaneuler/Experimentation/TransactionTrieCreator/TransactionTrieCreatorExperiment.java
  src/test/java/org/pawaneuler/Generator/TransactionLogGenerator/transactionLogTest2.tcsv
Labels: enhancement
